# FROM -> 베이스 이미지를 도커 허브에서 가져오기
FROM node:16-alpine

# WORKDIR -> 해당 소스 코드들이 들어가는 경로
WORKDIR /user/src/app

# 소스 코드가 바뀔 떄 마다 종속성까지 다시 복사해주는 수고를 덜기위헤
# 종속성 목록을 담고 있는 package.json을 먼저 복사
COPY package.json ./

# package.json에 명시 되어있는 종속성 설치
RUN npm install

# 이번에는 모든 소스 코드들을 WORKDI로 복사
COPY ./ ./

# CMD -> 이 컨테이너 실행 시 닽이 실행할 명령어
CMD [ "npm", "run", "start" ]